apiVersion: apps/v1
kind: Deployment
metadata:
  name: forcet-deployment
  namespace: forcet22-dev
  labels:
    app: forcet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forcet-app
  template:
    metadata:
      labels:
        app: forcet-app
    spec:
      containers:
        - name: forcet-node
          image: forcet22/hola-node:build-{{ tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: forcet-config
            - secretRef:
                name: forcet-secret
          startupProbe:
            httpGet:
              path: /startup
              port: 3000
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10